name: CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-docker-and-update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Run SpotBugs
        run: mvn spotbugs:check

      - name: Run Tests
        run: mvn test

      - name: Set up variables
        id: vars
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository }}/petclinic" >> $GITHUB_ENV
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "TAG=dev-${{ github.sha }}" >> $GITHUB_ENV
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "TAG=prod-${{ github.sha }}" >> $GITHUB_ENV
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t $IMAGE:$TAG -t $IMAGE:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: romangulyako/petclinic-infra
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra

      - name: Update Helm values
        run: |
          yq eval -i '.image.tag = env(TAG)' infra/environments/$ENVIRONMENT/petclinic-values.yaml

      - name: Commit and push changes
        run: |
          cd infra
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add environments/$ENVIRONMENT/petclinic-values.yaml
          git commit -m "Update PetClinic image to $IMAGE:$TAG for $ENVIRONMENT"
          git push origin main

      - name: Notify Telegram on Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "PetClinic CI Success! Pipeline completed."

      - name: Notify Telegram on Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "PetClinic CI Failed! Check logs."
